Streamkit/Models/ErrorViewModel.cs
using System;

namespace Streamkit.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Streamkit/Models/Users.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Streamkit.Database;
using MySql.Data.MySqlClient;

namespace Streamkit.Models
{
    public class User {
        private string userId;
        private string twitchId;
        private string twitchUsername;
    }

    
    public static class UserManager {
        public static User GetUser(string id) {
            throw new NotImplementedException();
        }

        public static void AddUser(string twitchId, string twitchUsername) {
            using (DatabaseConnection conn = new DatabaseConnection()) {
                // TODO...
                MySqlCommand cmd = new MySqlCommand();
                cmd.CommandText = "";
                cmd.Parameters.AddWithValue("", null);
                throw new NotImplementedException();
            }
        }
    }
}

Streamkit/Controllers/ConnectController.cs
using System;
using System.Net.Http;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

using Newtonsoft.Json.Linq;

using Streamkit.Web;

namespace Streamkit.Controllers
{
    public class ConnectController : Controller
    {
        public IActionResult Index()
        {
            // TODO: Map OAuth connection links to model.
            // TODO: Move OAuth logic to OAuth namespace after we get it working.
            HttpGetRequest req = new HttpGetRequest("todo url");
            req.AddParam("client_id", Config.TwitchOAuth.ClientId);
            req.AddParam("redirect_uri", Config.OAuthRedirect);
            req.AddParam("response_type", "code");
            req.AddParam("scope", Config.TwitchScope);
            req.AddParam("force_verify", "true");
            req.AddParam("state", null); // TODO: Generate token for this.

            JObject res = req.GetResponseJson();


            // TODO: ServiceConnectUrl class for storing the connection urls
            // to all OAuth services.
            ViewData["service_connect_url"] = null;

            return View();
        }
    }
}

Streamkit/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;

using Streamkit.Core;
using Streamkit.Web;
using Streamkit.Routes;

namespace Streamkit.Controllers
{
    public class HomeController : WebController
    {
        public IActionResult Index() {
            ActionRequestHandler req = new ActionRequestHandler(
                    this, HomeRoutes.Index);
            return req.Handle();
        }

        public IActionResult Privacy() {
            ActionRequestHandler req = new ActionRequestHandler(
                    this, HomeRoutes.Privacy);
            return req.Handle();
        }

        public IActionResult Subscribers() {
            ActionRequestHandler req = new ActionRequestHandler(
                    this, HomeRoutes.Subscribers);
            return req.Handle();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error() {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Streamkit/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;

using Streamkit.Routes;
using Streamkit.Web;

namespace Streamkit.Controllers {
    public class LoginController : WebController {
        public IActionResult Index() {
            ActionRequestHandler req = new ActionRequestHandler(
                    this, LoginRoutes.Index);
            return req.Handle();
        }

        public IActionResult Twitch() {
            ActionRequestHandler req = new ActionRequestHandler(
                    this, LoginRoutes.Twitch);
            return req.Handle();
        }
    }
}

Streamkit/Controllers/MyAccountController.cs
using Microsoft.AspNetCore.Mvc;

using Streamkit.Web;
using Streamkit.Routes;

namespace Streamkit.Controllers {
    public class MyAccountController : WebController {
        public IActionResult Index() {
            ActionRequestHandler req = new ActionRequestHandler(
                    this, MyAccountRoutes.Index);
            return req.Handle();
        }
    }
}

Streamkit/Controllers/StreamkitController.cs
using Microsoft.AspNetCore.Mvc;

using Streamkit.Web;
using Streamkit.Routes;

namespace Streamkit.Controllers
{
    public class StreamkitController : WebController
    {
        public IActionResult Index() {
            ActionRequestHandler req = new ActionRequestHandler(
                    this, StreamkitRoutes.Index);
            return req.Handle();
        }

        public IActionResult BitbarSource() {
            ActionRequestHandler req = new ActionRequestHandler(
                    this, StreamkitRoutes.BitbarSource);
            return req.Handle();
        }

        public IActionResult BitbarSubmit() {
            ActionRequestHandler req = new ActionRequestHandler(
                    this, StreamkitRoutes.BitbarSubmit);
            return req.Handle();
        }

        // TODO: Create API...
        public IActionResult GetBitbar() {
            ActionRequestHandler req = new ActionRequestHandler(
                    this, StreamkitRoutes.GetBitbar);
            return req.Handle();
        }
    }
}

Streamkit/Controllers/Web/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;

using Streamkit.Core;
using Streamkit.Web;
using Streamkit.Routes.Web;

namespace Streamkit.Controllers.Web
{
    public class HomeController : WebController
    {
        public IActionResult Index() {
            ActionRequestHandler req = new ActionRequestHandler(
                    this, HomeRoutes.Index);
            return req.Handle();
        }

        public IActionResult Privacy() {
            ActionRequestHandler req = new ActionRequestHandler(
                    this, HomeRoutes.Privacy);
            return req.Handle();
        }

        public IActionResult Subscribers() {
            ActionRequestHandler req = new ActionRequestHandler(
                    this, HomeRoutes.Subscribers);
            return req.Handle();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error() {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Streamkit/Controllers/Web/LoginController.cs
using Microsoft.AspNetCore.Mvc;

using Streamkit.Routes.Web;
using Streamkit.Web;

namespace Streamkit.Controllers.Web {
    public class LoginController : WebController {
        public IActionResult Index() {
            ActionRequestHandler req = new ActionRequestHandler(
                    this, LoginRoutes.Index);
            return req.Handle();
        }

        public IActionResult Twitch() {
            ActionRequestHandler req = new ActionRequestHandler(
                    this, LoginRoutes.Twitch);
            return req.Handle();
        }
    }
}

Streamkit/Controllers/Web/MyAccountController.cs
using Microsoft.AspNetCore.Mvc;

using Streamkit.Web;
using Streamkit.Routes.Web;

namespace Streamkit.Controllers.Web {
    public class MyAccountController : WebController {
        public IActionResult Index() {
            ActionRequestHandler req = new ActionRequestHandler(
                    this, MyAccountRoutes.Index);
            return req.Handle();
        }
    }
}

Streamkit/Controllers/Web/StreamkitController.cs
using Microsoft.AspNetCore.Mvc;

using Streamkit.Web;
using Streamkit.Routes.Web;

namespace Streamkit.Controllers.Web
{
    public class StreamkitController : WebController
    {
        public IActionResult Index() {
            ActionRequestHandler req = new ActionRequestHandler(
                    this, StreamkitRoutes.Index);
            return req.Handle();
        }

        public IActionResult BitbarSource() {
            ActionRequestHandler req = new ActionRequestHandler(
                    this, StreamkitRoutes.BitbarSource);
            return req.Handle();
        }

        public IActionResult BitbarSubmit() {
            ActionRequestHandler req = new ActionRequestHandler(
                    this, StreamkitRoutes.BitbarSubmit);
            return req.Handle();
        }
    }
}

Streamkit/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Go! Go! Mic!";
}

<partial name="_UnderConstruction" />

Streamkit/Views/Home/Subscribers.cshtml
@using Newtonsoft.Json.Linq

@{
    ViewData["Title"] = "Subscribers";
}

<div class="panel panel-default">
    <div class="panel panel-heading">Subscribers</div>

    @foreach (JToken sub in ViewBag.Subs) {   
        <div class="panel user-list-item">
            <a href="@("https://twitch.tv/" + (string)sub["user"]["name"])" class="nostyle">
                <div class="row row-flex vertical-hecking-centered">
                    <div class="col-md-2">
                        <img src="@((string)sub["user"]["logo"])" style="width: 128px;">
                    </div>

                    <div class="col-md-8 vertical-hecking-centered">
                        <div>
                            <span class="user-list-name"><strong>@((string)sub["user"]["display_name"])</strong></span><br/>
                            <span class="user-list-desc">@((string)sub["user"]["bio"])</span>
                        </div>
                    </div>
                </div>
            </a>
        </div>

    }
</div>
        

Streamkit/Views/Login/Index.cshtml
@{
    ViewData["Title"] = "Connect";
}

<div class="connect-service">
    <a href="@ViewBag.TwitchUrl" class="btn btn-primary">Login with Twitch</a>
</div>

<br/>

<partial name="_UnderConstruction" />

Streamkit/Views/MyAccount/Index.cshtml
@{
    ViewData["Title"] = "My Account";
}
<h2>You have successfully logged in, @ViewBag.Username</h2>

<br />

<partial name="_UnderConstruction" />

Streamkit/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Streamkit</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    @if (ViewBag.User != null) {
                        <span class="icon-bar"></span>
                    }
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">gogomic.co</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (ViewBag.User != null) {
                        <li><a asp-area="" asp-controller="Streamkit" asp-action="Index">Streamkit</a></li>
                    }
                    <li><a asp-area="" asp-controller="Home" asp-action="Subscribers">Subscribers</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a></li>
                    <li><a asp-area="" asp-controller="Login" asp-action="Index">Login</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />
    
    <br/>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @(DateTime.Now.Year) - Streamkit Beta 0.9.1</p>
        </footer>
    </div>
</body>
</html>

Streamkit/Views/Shared/_UnderConstruction.cshtml
<div class="panel panel-warning">
    <div class="panel panel-heading">Under Construction</div>
    <div class="panel-body">
        This section of the website is still under construction. Stay tuned for more content!
    </div>
</div>

Streamkit/Views/Streamkit/BitbarSource.cshtml
@{
    Layout = null;
}

<html>
<head>
    <link rel="stylesheet" href="~/css/bitbar.css" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/js/bitbar_source.js"></script>
    <script src="~/js/bitbar.js"></script>
</head>

    <body>
        <div id="container" class="bit-container">
            <div id="title" class="bit-text"></div>
            <div class="bit-canvas">
                <canvas id="canvas" width="457" height="49"></canvas>
            </div>
            <div id="count" class="bit-text"></div>
        </div>
    </body>
</html>

Streamkit/Views/Streamkit/Index.cshtml
@section Scripts {
    <script type="text/javascript" src="~/js/streamkit.js"></script>
}

<div class="panel panel-default">
    <div class="panel panel-heading">Bitbar</div>
    <div class="panel-body">
        <form method="post" runat="server" enctype="multipart/form-data" action="Streamkit/BitbarSubmit">
            <div class="form-group">
                <label for="value">Value</label>
                <input type="text" class="form-control small-input" name="value" value="@ViewBag.Bitbar.Value" /><br />
            </div>

            <div class="form-group">
                <label for="maxValue">Max value</label>
                <input type="text" class="form-control small-input" name="max_value" value="@ViewBag.Bitbar.MaxValue" /><br />
            </div>

            <div class="form-group">
                <label for="color">Target Color</label><br />
                <input type="color" id="target_color" value="@("#" + ViewBag.Bitbar.TargetColor)" /><br />
                <input type="text" id="target_color_hex" name="target_color" class="form-control small-input" value="@("#" + ViewBag.Bitbar.TargetColor)">
            </div>

            <div class="form-group">
                <label for="color">Fill Color</label><br />
                <input type="color" id="fill_color" value="@("#" + ViewBag.Bitbar.FillColor)" /><br />
                <input type="text" id="fill_color_hex" name="fill_color" class="form-control small-input" value="@("#" + ViewBag.Bitbar.FillColor)">
            </div>

            <hr />

            <div class="form-group">
                <label for="image">Image file</label>
                <input type="file" runat="server" name="image">
            </div>


            <div class="container-fluid">
                <div class="col-md-12 text-center">
                    <div class="btn-group" role="group">
                        <button class="btn btn-primary">Update</button>
                        <a href="/Streamkit/BitbarSource?id=@(ViewBag.Bitbar.Id)" class="btn btn-default">View Source</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>